<?php

namespace SpecShaper\GdprBundle\Types;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\ConversionException;
use Doctrine\DBAL\Types\Type;
use SpecShaper\GdprBundle\Model\PersonalData;

final class PersonalDataType extends Type
{
    public const NAME = 'personal_data';

    public function getName(): string
    {
        return self::NAME;
    }

    public function canRequireSQLConversion()
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function getSqlDeclaration(array $fieldDeclaration, AbstractPlatform $platform): string
    {
        return $platform->getClobTypeDeclarationSQL($fieldDeclaration);
    }

    public function convertToPHPValue($value, AbstractPlatform $platform): mixed
    {
        // This is executed when the value is read from the database. Make your conversions here, optionally using the $platform.
        if (null === $value) {
            return null;
        }

        $value = (is_resource($value)) ? stream_get_contents($value) : $value;

        return unserialize($value);
    }

    /**
     * @param PersonalData $value
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform): ?string
    {
        if (null === $value) {
            return null;
        }

        if (!$value instanceof PersonalData) {
            $value = (new PersonalData())->setData($value);
        }

        return serialize($value);
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform): bool
    {
        return true;
    }
}
