<?php

namespace SpecShaper\GdprBundle\Repository;

use Doctrine\ORM\Query;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends \Doctrine\ORM\EntityRepository
{


}
