<?php

namespace SpecShaper\GdprBundle\Utils;

use Symfony\Component\PropertyAccess\PropertyAccessor;
use Symfony\Component\PropertyAccess\PropertyAccessorInterface;

/**
 * Recursively resolves nested properties as generated by Embedddd entities.
 */
class ValueExtractor
{
    private PropertyAccessorInterface $accessor;

    public function __construct()
    {
        $this->accessor = new PropertyAccessor();
    }

    /**
     * Recursively resolve a dotted property path and extract the final value.
     *
     * Examples:
     *  - 'employeeID.ppsn'           => resolves ->getEmployeeID()->getPpsn()->getData()
     *  - 'embeddedEmployeeID.ppsn'   => same as above
     *
     * @param object $object The root object
     * @param string $path Dot-notated path to resolve
     * @return mixed|null The extracted value or null
     */
    public function extractValue(object $object, string $path): mixed
    {
        $segments = explode('.', $path);

        $current = $object;

        foreach ($segments as $segment) {
            if (null === $current) {
                return null;
            }

            if (!$this->accessor->isReadable($current, $segment)) {
                throw new \RuntimeException(sprintf(
                    'Cannot read property "%s" on class "%s".',
                    $segment,
                    get_class($current)
                ));
            }
            $current = $this->accessor->getValue($current, $segment);
        }
        return $current;
    }

    /**
     * Assign a value to the last property in a dotted path.
     *
     * Example:
     *   setValue($employeeRpn, 'embeddedEmployeeID.ppsn', $personalDataObj);
     *
     * @param object $object Root object
     * @param string $path Dot-notated path
     * @param mixed $value The value to set (e.g. PersonalData or string)
     */
    public function setValue(object $object, string $path, mixed $value): void
    {
        if (!$this->accessor->isWritable($object, $path)) {
            throw new \RuntimeException(sprintf(
                'Cannot write to property path "%s" on object of class "%s".',
                $path,
                get_class($object)
            ));
        }

        $this->accessor->setValue($object, $path, $value);
    }
}
